// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoT4S_01SiZ3KVFOVWk2ukGujVcSY0yec',
    appId: '1:452893516206:android:c87fc5ca5ad19c882ee83f',
    messagingSenderId: '452893516206',
    projectId: 'neighbourhood-library-app',
    storageBucket: 'neighbourhood-library-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoT4S_01SiZ3KVFOVWk2ukGujVcSY0yec',
    appId: '1:452893516206:android:c87fc5ca5ad19c882ee83f',
    messagingSenderId: '452893516206',
    projectId: 'neighbourhood-library-app',
    storageBucket: 'neighbourhood-library-app.firebasestorage.app',
    iosBundleId: 'com.example.aee_fyp3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoT4S_01SiZ3KVFOVWk2ukGujVcSY0yec',
    appId: '1:452893516206:android:c87fc5ca5ad19c882ee83f',
    messagingSenderId: '452893516206',
    projectId: 'neighbourhood-library-app',
    storageBucket: 'neighbourhood-library-app.firebasestorage.app',
    iosBundleId: 'com.example.aee_fyp3',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoT4S_01SiZ3KVFOVWk2ukGujVcSY0yec',
    appId: '1:452893516206:android:c87fc5ca5ad19c882ee83f',
    messagingSenderId: '452893516206',
    projectId: 'neighbourhood-library-app',
    storageBucket: 'neighbourhood-library-app.firebasestorage.app',
    authDomain: 'neighbourhood-library-app.firebaseapp.com',
    measurementId: 'G-XXXXXXXXXX', // Optional, replace with real if known
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoT4S_01SiZ3KVFOVWk2ukGujVcSY0yec',
    appId: '1:452893516206:android:c87fc5ca5ad19c882ee83f',
    messagingSenderId: '452893516206',
    projectId: 'neighbourhood-library-app',
    storageBucket: 'neighbourhood-library-app.firebasestorage.app',
    authDomain: 'neighbourhood-library-app.firebaseapp.com',
    measurementId: 'G-XXXXXXXXXX',
  );
}
